### ISSUE TITLE
Missing MOODLE_INTERNAL in lib.php

### ISSUE THREAD

**Issue by volodymyrdovhan** [3iPunt/moodle-mod_videoconnect#3]
Hello,
in lib.php should be defined defined('MOODLE_INTERNAL') || die();

Please review the documentation:
[https://moodledev.io/general/development/policies/codingstyle#require--include:~:text=defined('-,MOODLE_INTERNAL,-') ||](https://moodledev.io/general/development/policies/codingstyle#require--include:~:text=defined(%27-,MOODLE_INTERNAL,-%27)%20%7C%7C)

![image](https://github.com/user-attachments/assets/3dbe80a0-94a0-4d8b-b911-8490a203416a)

**Comment by volodymyrdovhan** [comment]
@abertranb this change not merged to the master
https://github.com/3iPunt/moodle-mod_videoconnect/blob/master/lib.php

**Comment by abertranb** [comment]
You are absolutely right, and I appreciate you pointing that out.

Thanks!
