### ISSUE TITLE
Instance deletion logic

### ISSUE THREAD

**Issue by volodymyrdovhan** [3iPunt/moodle-mod_videoconnect#8]
Hello,
1. Could you please explain the logic, of why you need to keep uploads history, but at the same time delete the module instance?
![image](https://github.com/user-attachments/assets/9be9e094-a408-4ae4-8565-3efe3364be38)

2. It is not recommended to use the execute() method. Only use it when no specialised method exists. 
https://moodledev.io/docs/4.5/apis/core/dml#execute
![image](https://github.com/user-attachments/assets/4b5fe7a9-3356-451b-920c-6684ad222a00)

**Comment by abertranb** [comment]
Thanks @volodymyrdovhan 

Hi @amanzano3ip and @ricardo3ipunt,

Could you confirm this? From what I see, the plugin seems designed to mark videos as deleted and includes a task to remove them from the external provider.

Currently, this functionality isn’t implemented. I suggest we remove this code for now and propose it as a new feature instead. With this feature, administrators could enable an option to delete videos once an instance is deleted, provided there are no other references to that video within the current Moodle site.

What do you think?

Thanks!

**Comment by abertranb** [comment]
The main idea es to delete al the data in the context of the current activity deleted
Best regards
