### ISSUE TITLE
Not implemented index.php page

### ISSUE THREAD

**Issue by volodymyrdovhan** [3iPunt/moodle-mod_videoconnect#9]
Hello,
I suppose it is not a blocker, but the index.php page is implemented in all standard and most custom modules.
Please consider its implementation to provide a common experience for other users.

![image](https://github.com/user-attachments/assets/847e1bf2-62bf-4a1d-8ce7-f282e5ce611d)

**Comment by abertranb** [comment]
Thanks @volodymyrdovhan
